# SPDX-License-Identifier: PMPL-1.0-or-later
defmodule HttpCapabilityGateway.MTLSTest do
  @moduledoc """
  Phase B (standards#97) -- mTLS as the primary trust-level path.

  These tests drive the certificate -> trust-level pipeline with a REAL
  test certificate authority (test/fixtures/mtls, regenerated by
  gen-test-ca.sh) rather than a hand-rolled tuple. They need no live TLS
  socket: the cert-parsing and trust-decision logic is exercised directly
  with DER decoded from the committed fixtures, and the CA trust invariant
  is proven at the crypto layer via :public_key.pkix_path_validation/3.

  The live mTLS handshake (verify_peer / fail_if_no_peer_cert) is a
  transport-level guarantee asserted by the listener configuration in
  HttpCapabilityGateway.Application; an end-to-end socket test across the
  gateway <-> BoJ seam is Phase C (standards#98) scope per the integration
  plan.
  """

  use ExUnit.Case, async: true

  alias HttpCapabilityGateway.Gateway

  @fixtures Path.join(__DIR__, "fixtures/mtls")

  defp der(name) do
    [{:Certificate, der, :not_encrypted} | _] =
      @fixtures
      |> Path.join(name)
      |> File.read!()
      |> :public_key.pem_decode()

    der
  end

  describe "extract_cert_subject/1 against the real test CA" do
    test "pulls O, OU, CN from an internal-services client cert" do
      assert {:ok, subject} = Gateway.extract_cert_subject(der("client-internal.crt"))
      assert subject.organization == "BoJ Test Estate"
      assert subject.organizational_unit == "Internal Services"
      assert subject.common_name == "internal-svc"
    end

    test "pulls a non-internal OU from an ordinary authenticated client cert" do
      assert {:ok, subject} = Gateway.extract_cert_subject(der("client-auth.crt"))
      assert subject.organizational_unit == "Application"
      assert subject.common_name == "regular-client"
    end

    test "returns a clean error on malformed DER instead of crashing" do
      assert {:error, :decode_failed} = Gateway.extract_cert_subject(<<0, 1, 2, 3, 4, 5>>)
    end
  end

  describe "determine_trust_level_from_cert/2" do
    test "verified internal-services cert -> internal" do
      {:ok, subject} = Gateway.extract_cert_subject(der("client-internal.crt"))
      assert Gateway.determine_trust_level_from_cert(subject, true) == "internal"
    end

    test "verified ordinary cert -> authenticated" do
      {:ok, subject} = Gateway.extract_cert_subject(der("client-auth.crt"))
      assert Gateway.determine_trust_level_from_cert(subject, true) == "authenticated"
    end

    test "unverified cert is never trusted, even with the internal OU" do
      {:ok, subject} = Gateway.extract_cert_subject(der("client-internal.crt"))
      assert Gateway.determine_trust_level_from_cert(subject, false) == "untrusted"
    end
  end

  describe "CA trust invariant (transport verify_peer at the crypto layer)" do
    test "a client cert chaining to the configured CA path-validates" do
      assert {:ok, _} =
               :public_key.pkix_path_validation(
                 der("ca.crt"),
                 [der("client-internal.crt")],
                 []
               )
    end

    test "a client cert signed by an unrelated CA is rejected" do
      assert {:error, _} =
               :public_key.pkix_path_validation(
                 der("ca.crt"),
                 [der("client-rogue.crt")],
                 []
               )
    end
  end
end
